// Central native GameplayTag declarations for Hellwake.
#pragma once

#include "NativeGameplayTags.h"

namespace HellwakeTags
{
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Heavy);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Emberbrand);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Bulwark);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ruinfall);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WakeOfHell);

	// Native cooldown tags let the first playable C++ slice enforce all
	// cooldowns without waiting for Blueprint GameplayEffect children.
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_LightAttack);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_HeavyAttack);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dodge);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Emberbrand);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bulwark);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ruinfall);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_WakeOfHell);

	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss_GravewardenPhase_SweepingAxe);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss_GravewardenPhase_GroundSlam);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss_GravewardenPhase_AreaDenial);

	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cinematic);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_IFrame);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AbilityCooldown);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AttackCone_Light);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AttackCone_Heavy);

	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Ember);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Fortified);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_SoulrendAura);

	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage_Taken);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage_Dealt);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage_Crit);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Loot_Dropped);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Loot_PickedUp);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Encounter_StageChanged);

	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Role_Reaver);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Role_Wraith);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Role_Acolyte);
	HELLWAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Role_Gravewarden);
}
